[phases.setup]
# Include PHP 8.3 and build essentials
nixPkgs = ["php83", "php83Extensions.curl", "php83Extensions.zip", "curl", "unzip"]

[phases.build]
# Install Composer manually and PHP dependencies
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "composer install --no-dev --optimize-autoloader"
]

[start]
# Serve from current directory (since you don't have a /public folder)
cmd = "php -S 0.0.0.0:$PORT -t ."