[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.curl",
  "php83Extensions.zip",
  "curl",
  "unzip"
]

[phases.build]
cmds = [
  "echo 'Installing Composer...'",
  # Install composer to /usr/bin instead of /usr/local/bin
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer",
  "echo 'Running composer install...'",
  "/usr/bin/composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t ."