[phases.setup]
nixPkgs = ["php83", "zip", "curl", "unzip"]

[phases.build]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."