[phases.setup]
nixPkgs = ["php83", "php83Extensions.curl", "php83Extensions.zip", "curl", "unzip"]

[phases.build]
cmds = [
  # Download and install Composer manually
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  # Run Composer install
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t ."