[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.simple"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"