[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "chmod +x start_railway.sh && ./start_railway.sh"

[env]
PORT = "8000"