[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "php setup.php && php -S 0.0.0.0:${PORT:-8000} index.php"

[env]
PORT = "8000"