[project]
name = "ticket-management"

[build]
builder = "dockerfile"

[run]
command = "php -S 0.0.0.0:${PORT:-8080} -t ."

[deploy]
start_command = "php -S 0.0.0.0:${PORT:-8080} -t ."
healthcheck_path = "/"
healthcheck_timeout = 30
restart_policy_type = "on_failure"
restart_policy_max_retries = 3

[env]
PORT = "8000"